### ISSUE TITLE
在1.9下编译失败

### ISSUE THREAD

**Issue by Rarpainting** [wyh267/FalconEngine#4]
1.9版本如下
```sh
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zhan/gopath:/home/zhan/project/searchThirdParty/falconEngine"
GORACE=""
GOROOT="/usr/local/go1.9rc2"
GOTOOLDIR="/usr/local/go1.9rc2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build833253239=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
错误信息如下：
```
# utils
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb62668, 0x16)
        /usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc44d6e0000, 0x100000, 0xee3f00, 0xf05378)
        /usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0xee3f40, 0x100000, 0x7f56ed00b8f8)
        /usr/local/go/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0xee3f40, 0x9, 0x0)
        /usr/local/go/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0xee3f40, 0x9, 0xf05388, 0x7f56ed00b8f8)
        /usr/local/go/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0xee3f40, 0x9, 0x200000077, 0x7f56ed00b8f8)
        /usr/local/go/src/runtime/mheap.go:666 +0x118
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0x7ffc73eb0288)
        /usr/local/go/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0xee3f40, 0x9, 0x7f56ed010077, 0x7f56ed00b8f8)
        /usr/local/go/src/runtime/mheap.go:732 +0xa1
runtime.(*mcentral).grow(0xee7050, 0x0)
        /usr/local/go/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0xee7050, 0x7f56ed00b8f8)
        /usr/local/go/src/runtime/mcentral.go:106 +0x33a
runtime.(*mcache).refill(0x7f56edb09000, 0x10000c420000777, 0x7f56ed00b8f8)
        /usr/local/go/src/runtime/mcache.go:123 +0xa4
runtime.(*mcache).nextFree.func1()
        /usr/local/go/src/runtime/malloc.go:557 +0x32
runtime.systemstack(0xed2f00)
        /usr/local/go/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1125

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:298 fp=0xc444505788 sp=0xc444505780 pc=0x455170
runtime.(*mcache).nextFree(0x7f56edb09000, 0x77, 0xc44d6ce000, 0x7f56ed00b8f8, 0x1)
        /usr/local/go/src/runtime/malloc.go:556 +0xa9 fp=0xc4445057e0 sp=0xc444505788 pc=0x40fca9
runtime.mallocgc(0x4800, 0xb1aa20, 0x1, 0xc44d6db800)
        /usr/local/go/src/runtime/malloc.go:711 +0x6fa fp=0xc444505888 sp=0xc4445057e0 pc=0x41057a
runtime.makeslice(0xb1aa20, 0x0, 0x449, 0xc44d6db800, 0x0, 0x44a)
        /usr/local/go/src/runtime/slice.go:54 +0x77 fp=0xc4445058b8 sp=0xc444505888 pc=0x43f157
cmd/compile/internal/ssa.(*regAllocState).computeLive(0xc424714000)
        /usr/local/go/src/cmd/compile/internal/ssa/regalloc.go:2330 +0x17ed fp=0xc444505be0 sp=0xc4445058b8 pc=0x60c21d
cmd/compile/internal/ssa.(*regAllocState).init(0xc424714000, 0xc421898280)
        /usr/local/go/src/cmd/compile/internal/ssa/regalloc.go:613 +0x702 fp=0xc444505c90 sp=0xc444505be0 pc=0x5fcf32
cmd/compile/internal/ssa.regalloc(0xc421898280)
        /usr/local/go/src/cmd/compile/internal/ssa/regalloc.go:143 +0x4a fp=0xc444505cb8 sp=0xc444505c90 pc=0x5fac5a
cmd/compile/internal/ssa.Compile(0xc421898280)
        /usr/local/go/src/cmd/compile/internal/ssa/compile.go:70 +0x2bb fp=0xc4445095f0 sp=0xc444505cb8 pc=0x5cb19b
cmd/compile/internal/gc.buildssa(0xc420c4e9a0, 0x0, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/ssa.go:212 +0xd89 fp=0xc444509750 sp=0xc4445095f0 pc=0x9f6919
cmd/compile/internal/gc.compileSSA(0xc420c4e9a0, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:240 +0x3c fp=0xc4445097c8 sp=0xc444509750 pc=0x9c34bc
cmd/compile/internal/gc.compile(0xc420c4e9a0)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:219 +0x218 fp=0xc444509828 sp=0xc4445097c8 pc=0x9c33e8
cmd/compile/internal/gc.funccompile(0xc420c4e9a0)
        /usr/local/go/src/cmd/compile/internal/gc/dcl.go:1049 +0xb7 fp=0xc444509880 sp=0xc444509828 pc=0x969e87
cmd/compile/internal/gc.Main(0xb73f98)
        /usr/local/go/src/cmd/compile/internal/gc/main.go:585 +0x29d2 fp=0xc444509f08 sp=0xc444509880 pc=0x99e152
main.main()
        /usr/local/go/src/cmd/compile/main.go:49 +0x95 fp=0xc444509f80 sp=0xc444509f08 pc=0xabddf5
runtime.main()
        /usr/local/go/src/runtime/proc.go:185 +0x20d fp=0xc444509fe0 sp=0xc444509f80 pc=0x42bedd
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc444509fe8 sp=0xc444509fe0 pc=0x457cf1
```

附：在1.8版本下编译成功

**Comment by justinzhu** [comment]
这个有可能是go编译器的bug，我在用go1.9编译的时候也遇到了这个问题，把zi.go中的init函数的内容注释掉就能编译通过
